//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets6EEBBCA9995821167F5F628514616F38B587BDBC88BC4C858CE6D81B222E5B16))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets6EEBBCA9995821167F5F628514616F38B587BDBC88BC4C858CE6D81B222E5B16 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets6EEBBCA9995821167F5F628514616F38B587BDBC88BC4C858CE6D81B222E5B16()
        {
            this.EdmEntityContainerName = "DBIntegrationEntities";
            this.StoreEntityContainerName = "DBIntegrationModelDomainStoreContainer";
            this.HashOverMappingClosure = "0f1a6c35e70511e456a58c09a04c196a43059c7b6043af7d0abd58025e7fa8cc";
            this.HashOverAllExtentViews = "f546601f286f8aeadb735fa1e26dafc712f77959982ca15e92576613ac95f229";
            this.ViewCount = 12;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for DBIntegrationModelDomainStoreContainer.Address
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DBIntegrationModelDomainStoreContainer.Address", @"
    SELECT VALUE -- Constructing Address
        [DBIntegrationModel.Domain.Store.Address](T1.Address_AddressId, T1.Address_SiteId, T1.Address_AddressTypeId, T1.Address_AddressLine1, T1.Address_AddressLine2, T1.Address_AddressLine3, T1.Address_City, T1.Address_StateProvinceRegionId, T1.Address_PostalCode, T1.Address_CountryRegionId, T1.Address_CreatedDateTime, T1.Address_CreatedBy, T1.Address_ModifiedDateTime, T1.Address_ModifiedBy)
    FROM (
        SELECT 
            T.AddressId AS Address_AddressId, 
            T.SiteId AS Address_SiteId, 
            T.AddressTypeId AS Address_AddressTypeId, 
            T.AddressLine1 AS Address_AddressLine1, 
            T.AddressLine2 AS Address_AddressLine2, 
            T.AddressLine3 AS Address_AddressLine3, 
            T.City AS Address_City, 
            T.StateProvinceRegionId AS Address_StateProvinceRegionId, 
            T.PostalCode AS Address_PostalCode, 
            T.CountryRegionId AS Address_CountryRegionId, 
            T.CreatedDateTime AS Address_CreatedDateTime, 
            T.CreatedBy AS Address_CreatedBy, 
            T.ModifiedDateTime AS Address_ModifiedDateTime, 
            T.ModifiedBy AS Address_ModifiedBy, 
            True AS _from0
        FROM DBIntegrationEntities.Addresses AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DBIntegrationEntities.Addresses
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DBIntegrationEntities.Addresses", @"
    SELECT VALUE -- Constructing Addresses
        [DBIntegrationModel.Domain.Address](T1.Address_AddressId, T1.Address_SiteId, T1.Address_AddressTypeId, T1.Address_AddressLine1, T1.Address_AddressLine2, T1.Address_AddressLine3, T1.Address_City, T1.Address_StateProvinceRegionId, T1.Address_PostalCode, T1.Address_CountryRegionId, T1.Address_CreatedDateTime, T1.Address_CreatedBy, T1.Address_ModifiedDateTime, T1.Address_ModifiedBy)
    FROM (
        SELECT 
            T.AddressId AS Address_AddressId, 
            T.SiteId AS Address_SiteId, 
            T.AddressTypeId AS Address_AddressTypeId, 
            T.AddressLine1 AS Address_AddressLine1, 
            T.AddressLine2 AS Address_AddressLine2, 
            T.AddressLine3 AS Address_AddressLine3, 
            T.City AS Address_City, 
            T.StateProvinceRegionId AS Address_StateProvinceRegionId, 
            T.PostalCode AS Address_PostalCode, 
            T.CountryRegionId AS Address_CountryRegionId, 
            T.CreatedDateTime AS Address_CreatedDateTime, 
            T.CreatedBy AS Address_CreatedBy, 
            T.ModifiedDateTime AS Address_ModifiedDateTime, 
            T.ModifiedBy AS Address_ModifiedBy, 
            True AS _from0
        FROM DBIntegrationModelDomainStoreContainer.Address AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DBIntegrationModelDomainStoreContainer.Organization
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DBIntegrationModelDomainStoreContainer.Organization", @"
    SELECT VALUE -- Constructing Organization
        [DBIntegrationModel.Domain.Store.Organization](T1.Organization_OrganizationId, T1.Organization_OrganizationCode, T1.Organization_OrganizationName, T1.Organization_PhoneNumber, T1.Organization_FaxNumber, T1.Organization_ParentOrganizationCode, T1.Organization_Theme, T1.Organization_Skin, T1.Organization_Active, T1.Organization_DELETED, T1.Organization_CreatedDateTime, T1.Organization_CreatedBy, T1.Organization_ModifiedDateTime, T1.Organization_ModifiedBy)
    FROM (
        SELECT 
            T.OrganizationId AS Organization_OrganizationId, 
            T.OrganizationCode AS Organization_OrganizationCode, 
            T.OrganizationName AS Organization_OrganizationName, 
            T.PhoneNumber AS Organization_PhoneNumber, 
            T.FaxNumber AS Organization_FaxNumber, 
            T.ParentOrganizationCode AS Organization_ParentOrganizationCode, 
            T.Theme AS Organization_Theme, 
            T.Skin AS Organization_Skin, 
            T.Active AS Organization_Active, 
            T.DELETED AS Organization_DELETED, 
            T.CreatedDateTime AS Organization_CreatedDateTime, 
            T.CreatedBy AS Organization_CreatedBy, 
            T.ModifiedDateTime AS Organization_ModifiedDateTime, 
            T.ModifiedBy AS Organization_ModifiedBy, 
            True AS _from0
        FROM DBIntegrationEntities.Organizations AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DBIntegrationEntities.Organizations
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DBIntegrationEntities.Organizations", @"
    SELECT VALUE -- Constructing Organizations
        [DBIntegrationModel.Domain.Organization](T1.Organization_OrganizationId, T1.Organization_OrganizationCode, T1.Organization_OrganizationName, T1.Organization_PhoneNumber, T1.Organization_FaxNumber, T1.Organization_ParentOrganizationCode, T1.Organization_Theme, T1.Organization_Skin, T1.Organization_Active, T1.Organization_DELETED, T1.Organization_CreatedDateTime, T1.Organization_CreatedBy, T1.Organization_ModifiedDateTime, T1.Organization_ModifiedBy)
    FROM (
        SELECT 
            T.OrganizationId AS Organization_OrganizationId, 
            T.OrganizationCode AS Organization_OrganizationCode, 
            T.OrganizationName AS Organization_OrganizationName, 
            T.PhoneNumber AS Organization_PhoneNumber, 
            T.FaxNumber AS Organization_FaxNumber, 
            T.ParentOrganizationCode AS Organization_ParentOrganizationCode, 
            T.Theme AS Organization_Theme, 
            T.Skin AS Organization_Skin, 
            T.Active AS Organization_Active, 
            T.DELETED AS Organization_DELETED, 
            T.CreatedDateTime AS Organization_CreatedDateTime, 
            T.CreatedBy AS Organization_CreatedBy, 
            T.ModifiedDateTime AS Organization_ModifiedDateTime, 
            T.ModifiedBy AS Organization_ModifiedBy, 
            True AS _from0
        FROM DBIntegrationModelDomainStoreContainer.Organization AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DBIntegrationModelDomainStoreContainer.Person
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DBIntegrationModelDomainStoreContainer.Person", @"
    SELECT VALUE -- Constructing Person
        [DBIntegrationModel.Domain.Store.Person](T1.Person_UserId, T1.Person_OrganizationId, T1.Person_UserTypeId, T1.Person_FirstName, T1.Person_LastName, T1.Person_PhoneNumber, T1.Person_EmailAddress, T1.Person_UnitName, T1.Person_UnitNumber, T1.Person_Department, T1.Person_CreatedDateTime, T1.Person_CreatedBy, T1.Person_ModifiedDateTime, T1.Person_ModifiedBy)
    FROM (
        SELECT 
            T.UserId AS Person_UserId, 
            T.OrganizationId AS Person_OrganizationId, 
            T.UserTypeId AS Person_UserTypeId, 
            T.FirstName AS Person_FirstName, 
            T.LastName AS Person_LastName, 
            T.PhoneNumber AS Person_PhoneNumber, 
            T.EmailAddress AS Person_EmailAddress, 
            T.UnitName AS Person_UnitName, 
            T.UnitNumber AS Person_UnitNumber, 
            T.Department AS Person_Department, 
            T.CreatedDateTime AS Person_CreatedDateTime, 
            T.CreatedBy AS Person_CreatedBy, 
            T.ModifiedDateTime AS Person_ModifiedDateTime, 
            T.ModifiedBy AS Person_ModifiedBy, 
            True AS _from0
        FROM DBIntegrationEntities.People AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DBIntegrationEntities.People
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DBIntegrationEntities.People", @"
    SELECT VALUE -- Constructing People
        [DBIntegrationModel.Domain.Person](T1.Person_UserId, T1.Person_OrganizationId, T1.Person_UserTypeId, T1.Person_FirstName, T1.Person_LastName, T1.Person_PhoneNumber, T1.Person_EmailAddress, T1.Person_UnitName, T1.Person_UnitNumber, T1.Person_Department, T1.Person_CreatedDateTime, T1.Person_CreatedBy, T1.Person_ModifiedDateTime, T1.Person_ModifiedBy)
    FROM (
        SELECT 
            T.UserId AS Person_UserId, 
            T.OrganizationId AS Person_OrganizationId, 
            T.UserTypeId AS Person_UserTypeId, 
            T.FirstName AS Person_FirstName, 
            T.LastName AS Person_LastName, 
            T.PhoneNumber AS Person_PhoneNumber, 
            T.EmailAddress AS Person_EmailAddress, 
            T.UnitName AS Person_UnitName, 
            T.UnitNumber AS Person_UnitNumber, 
            T.Department AS Person_Department, 
            T.CreatedDateTime AS Person_CreatedDateTime, 
            T.CreatedBy AS Person_CreatedBy, 
            T.ModifiedDateTime AS Person_ModifiedDateTime, 
            T.ModifiedBy AS Person_ModifiedBy, 
            True AS _from0
        FROM DBIntegrationModelDomainStoreContainer.Person AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DBIntegrationModelDomainStoreContainer.Site
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DBIntegrationModelDomainStoreContainer.Site", @"
    SELECT VALUE -- Constructing Site
        [DBIntegrationModel.Domain.Store.Site](T1.Site_SiteId, T1.Site_OrganizationId, T1.Site_SiteTypeId, T1.Site_SiteName, T1.Site_SiteCode, T1.Site_TimeZoneId, T1.Site_CreatedDateTime, T1.Site_CreatedBy, T1.Site_ModifiedDateTime, T1.Site_ModifiedBy)
    FROM (
        SELECT 
            T.SiteId AS Site_SiteId, 
            T.OrganizationId AS Site_OrganizationId, 
            T.SiteTypeId AS Site_SiteTypeId, 
            T.SiteName AS Site_SiteName, 
            T.SiteCode AS Site_SiteCode, 
            T.TimeZoneId AS Site_TimeZoneId, 
            T.CreatedDateTime AS Site_CreatedDateTime, 
            T.CreatedBy AS Site_CreatedBy, 
            T.ModifiedDateTime AS Site_ModifiedDateTime, 
            T.ModifiedBy AS Site_ModifiedBy, 
            True AS _from0
        FROM DBIntegrationEntities.Sites AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DBIntegrationEntities.Sites
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DBIntegrationEntities.Sites", @"
    SELECT VALUE -- Constructing Sites
        [DBIntegrationModel.Domain.Site](T1.Site_SiteId, T1.Site_OrganizationId, T1.Site_SiteTypeId, T1.Site_SiteName, T1.Site_SiteCode, T1.Site_TimeZoneId, T1.Site_CreatedDateTime, T1.Site_CreatedBy, T1.Site_ModifiedDateTime, T1.Site_ModifiedBy)
    FROM (
        SELECT 
            T.SiteId AS Site_SiteId, 
            T.OrganizationId AS Site_OrganizationId, 
            T.SiteTypeId AS Site_SiteTypeId, 
            T.SiteName AS Site_SiteName, 
            T.SiteCode AS Site_SiteCode, 
            T.TimeZoneId AS Site_TimeZoneId, 
            T.CreatedDateTime AS Site_CreatedDateTime, 
            T.CreatedBy AS Site_CreatedBy, 
            T.ModifiedDateTime AS Site_ModifiedDateTime, 
            T.ModifiedBy AS Site_ModifiedBy, 
            True AS _from0
        FROM DBIntegrationModelDomainStoreContainer.Site AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DBIntegrationModelDomainStoreContainer.SiteType
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DBIntegrationModelDomainStoreContainer.SiteType", @"
    SELECT VALUE -- Constructing SiteType
        [DBIntegrationModel.Domain.Store.SiteType](T1.SiteType_SiteTypeId, T1.SiteType_SiteTypeName, T1.SiteType_CreatedDateTime, T1.SiteType_CreatedBy, T1.SiteType_ModifiedDateTime, T1.SiteType_ModifiedBy)
    FROM (
        SELECT 
            T.SiteTypeId AS SiteType_SiteTypeId, 
            T.SiteTypeName AS SiteType_SiteTypeName, 
            T.CreatedDateTime AS SiteType_CreatedDateTime, 
            T.CreatedBy AS SiteType_CreatedBy, 
            T.ModifiedDateTime AS SiteType_ModifiedDateTime, 
            T.ModifiedBy AS SiteType_ModifiedBy, 
            True AS _from0
        FROM DBIntegrationEntities.SiteTypes AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DBIntegrationEntities.SiteTypes
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DBIntegrationEntities.SiteTypes", @"
    SELECT VALUE -- Constructing SiteTypes
        [DBIntegrationModel.Domain.SiteType](T1.SiteType_SiteTypeId, T1.SiteType_SiteTypeName, T1.SiteType_CreatedDateTime, T1.SiteType_CreatedBy, T1.SiteType_ModifiedDateTime, T1.SiteType_ModifiedBy)
    FROM (
        SELECT 
            T.SiteTypeId AS SiteType_SiteTypeId, 
            T.SiteTypeName AS SiteType_SiteTypeName, 
            T.CreatedDateTime AS SiteType_CreatedDateTime, 
            T.CreatedBy AS SiteType_CreatedBy, 
            T.ModifiedDateTime AS SiteType_ModifiedDateTime, 
            T.ModifiedBy AS SiteType_ModifiedBy, 
            True AS _from0
        FROM DBIntegrationModelDomainStoreContainer.SiteType AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DBIntegrationModelDomainStoreContainer.UserType
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DBIntegrationModelDomainStoreContainer.UserType", @"
    SELECT VALUE -- Constructing UserType
        [DBIntegrationModel.Domain.Store.UserType](T1.UserType_UserTypeId, T1.UserType_UserTypeName, T1.UserType_CreatedDateTime, T1.UserType_CreatedBy, T1.UserType_ModifiedDateTime, T1.UserType_ModifiedBy)
    FROM (
        SELECT 
            T.UserTypeId AS UserType_UserTypeId, 
            T.UserTypeName AS UserType_UserTypeName, 
            T.CreatedDateTime AS UserType_CreatedDateTime, 
            T.CreatedBy AS UserType_CreatedBy, 
            T.ModifiedDateTime AS UserType_ModifiedDateTime, 
            T.ModifiedBy AS UserType_ModifiedBy, 
            True AS _from0
        FROM DBIntegrationEntities.UserTypes AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DBIntegrationEntities.UserTypes
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DBIntegrationEntities.UserTypes", @"
    SELECT VALUE -- Constructing UserTypes
        [DBIntegrationModel.Domain.UserType](T1.UserType_UserTypeId, T1.UserType_UserTypeName, T1.UserType_CreatedDateTime, T1.UserType_CreatedBy, T1.UserType_ModifiedDateTime, T1.UserType_ModifiedBy)
    FROM (
        SELECT 
            T.UserTypeId AS UserType_UserTypeId, 
            T.UserTypeName AS UserType_UserTypeName, 
            T.CreatedDateTime AS UserType_CreatedDateTime, 
            T.CreatedBy AS UserType_CreatedBy, 
            T.ModifiedDateTime AS UserType_ModifiedDateTime, 
            T.ModifiedBy AS UserType_ModifiedBy, 
            True AS _from0
        FROM DBIntegrationModelDomainStoreContainer.UserType AS T
    ) AS T1");
        }
    }
}
