//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCustomerIntegration2.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public long OrganizationId { get; set; }
        public string OrganizationCode { get; set; }
        public string OrganizationName { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string ParentOrganizationCode { get; set; }
        public string Theme { get; set; }
        public string Skin { get; set; }
        public bool Active { get; set; }
        public bool DELETED { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string ModifiedBy { get; set; }
    }
}
