//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace NewCustomerIntegration.Models.Domain
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CustomerDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CustomerDataEntities object using the connection string found in the 'CustomerDataEntities' section of the application configuration file.
        /// </summary>
        public CustomerDataEntities() : base("name=CustomerDataEntities", "CustomerDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CustomerDataEntities object.
        /// </summary>
        public CustomerDataEntities(string connectionString) : base(connectionString, "CustomerDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CustomerDataEntities object.
        /// </summary>
        public CustomerDataEntities(EntityConnection connection) : base(connection, "CustomerDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Address> Addresses
        {
            get
            {
                if ((_Addresses == null))
                {
                    _Addresses = base.CreateObjectSet<Address>("Addresses");
                }
                return _Addresses;
            }
        }
        private ObjectSet<Address> _Addresses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BusinessRule> BusinessRules
        {
            get
            {
                if ((_BusinessRules == null))
                {
                    _BusinessRules = base.CreateObjectSet<BusinessRule>("BusinessRules");
                }
                return _BusinessRules;
            }
        }
        private ObjectSet<BusinessRule> _BusinessRules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Option> Options
        {
            get
            {
                if ((_Options == null))
                {
                    _Options = base.CreateObjectSet<Option>("Options");
                }
                return _Options;
            }
        }
        private ObjectSet<Option> _Options;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Organization> Organizations
        {
            get
            {
                if ((_Organizations == null))
                {
                    _Organizations = base.CreateObjectSet<Organization>("Organizations");
                }
                return _Organizations;
            }
        }
        private ObjectSet<Organization> _Organizations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Site> Sites
        {
            get
            {
                if ((_Sites == null))
                {
                    _Sites = base.CreateObjectSet<Site>("Sites");
                }
                return _Sites;
            }
        }
        private ObjectSet<Site> _Sites;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Addresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAddresses(Address address)
        {
            base.AddObject("Addresses", address);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BusinessRules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBusinessRules(BusinessRule businessRule)
        {
            base.AddObject("BusinessRules", businessRule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Options EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOptions(Option option)
        {
            base.AddObject("Options", option);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Organizations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrganizations(Organization organization)
        {
            base.AddObject("Organizations", organization);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSites(Site site)
        {
            base.AddObject("Sites", site);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerDataModel.Domain", Name="Address")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Address : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="addressId">Initial value of the AddressId property.</param>
        /// <param name="siteId">Initial value of the SiteId property.</param>
        /// <param name="addressType">Initial value of the AddressType property.</param>
        public static Address CreateAddress(global::System.Int32 addressId, global::System.Int32 siteId, global::System.Int32 addressType)
        {
            Address address = new Address();
            address.AddressId = addressId;
            address.SiteId = siteId;
            address.AddressType = addressType;
            return address;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddressId
        {
            get
            {
                return _AddressId;
            }
            set
            {
                if (_AddressId != value)
                {
                    OnAddressIdChanging(value);
                    ReportPropertyChanging("AddressId");
                    _AddressId = StructuralObject.SetValidValue(value, "AddressId");
                    ReportPropertyChanged("AddressId");
                    OnAddressIdChanged();
                }
            }
        }
        private global::System.Int32 _AddressId;
        partial void OnAddressIdChanging(global::System.Int32 value);
        partial void OnAddressIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteId
        {
            get
            {
                return _SiteId;
            }
            set
            {
                OnSiteIdChanging(value);
                ReportPropertyChanging("SiteId");
                _SiteId = StructuralObject.SetValidValue(value, "SiteId");
                ReportPropertyChanged("SiteId");
                OnSiteIdChanged();
            }
        }
        private global::System.Int32 _SiteId;
        partial void OnSiteIdChanging(global::System.Int32 value);
        partial void OnSiteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddressType
        {
            get
            {
                return _AddressType;
            }
            set
            {
                OnAddressTypeChanging(value);
                ReportPropertyChanging("AddressType");
                _AddressType = StructuralObject.SetValidValue(value, "AddressType");
                ReportPropertyChanged("AddressType");
                OnAddressTypeChanged();
            }
        }
        private global::System.Int32 _AddressType;
        partial void OnAddressTypeChanging(global::System.Int32 value);
        partial void OnAddressTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddressLine1
        {
            get
            {
                return _AddressLine1;
            }
            set
            {
                OnAddressLine1Changing(value);
                ReportPropertyChanging("AddressLine1");
                _AddressLine1 = StructuralObject.SetValidValue(value, true, "AddressLine1");
                ReportPropertyChanged("AddressLine1");
                OnAddressLine1Changed();
            }
        }
        private global::System.String _AddressLine1;
        partial void OnAddressLine1Changing(global::System.String value);
        partial void OnAddressLine1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddressLine2
        {
            get
            {
                return _AddressLine2;
            }
            set
            {
                OnAddressLine2Changing(value);
                ReportPropertyChanging("AddressLine2");
                _AddressLine2 = StructuralObject.SetValidValue(value, true, "AddressLine2");
                ReportPropertyChanged("AddressLine2");
                OnAddressLine2Changed();
            }
        }
        private global::System.String _AddressLine2;
        partial void OnAddressLine2Changing(global::System.String value);
        partial void OnAddressLine2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddressLine3
        {
            get
            {
                return _AddressLine3;
            }
            set
            {
                OnAddressLine3Changing(value);
                ReportPropertyChanging("AddressLine3");
                _AddressLine3 = StructuralObject.SetValidValue(value, true, "AddressLine3");
                ReportPropertyChanged("AddressLine3");
                OnAddressLine3Changed();
            }
        }
        private global::System.String _AddressLine3;
        partial void OnAddressLine3Changing(global::System.String value);
        partial void OnAddressLine3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true, "City");
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StateProvince
        {
            get
            {
                return _StateProvince;
            }
            set
            {
                OnStateProvinceChanging(value);
                ReportPropertyChanging("StateProvince");
                _StateProvince = StructuralObject.SetValidValue(value, true, "StateProvince");
                ReportPropertyChanged("StateProvince");
                OnStateProvinceChanged();
            }
        }
        private global::System.String _StateProvince;
        partial void OnStateProvinceChanging(global::System.String value);
        partial void OnStateProvinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, "PostalCode");
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private Nullable<global::System.Int64> _PostalCode;
        partial void OnPostalCodeChanging(Nullable<global::System.Int64> value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CountryRegion
        {
            get
            {
                return _CountryRegion;
            }
            set
            {
                OnCountryRegionChanging(value);
                ReportPropertyChanging("CountryRegion");
                _CountryRegion = StructuralObject.SetValidValue(value, true, "CountryRegion");
                ReportPropertyChanged("CountryRegion");
                OnCountryRegionChanged();
            }
        }
        private global::System.String _CountryRegion;
        partial void OnCountryRegionChanging(global::System.String value);
        partial void OnCountryRegionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerDataModel.Domain", Name="BusinessRule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BusinessRule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BusinessRule object.
        /// </summary>
        /// <param name="ruleId">Initial value of the RuleId property.</param>
        /// <param name="ruleName">Initial value of the RuleName property.</param>
        /// <param name="ruleValue">Initial value of the RuleValue property.</param>
        public static BusinessRule CreateBusinessRule(global::System.Int64 ruleId, global::System.String ruleName, global::System.String ruleValue)
        {
            BusinessRule businessRule = new BusinessRule();
            businessRule.RuleId = ruleId;
            businessRule.RuleName = ruleName;
            businessRule.RuleValue = ruleValue;
            return businessRule;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RuleId
        {
            get
            {
                return _RuleId;
            }
            set
            {
                if (_RuleId != value)
                {
                    OnRuleIdChanging(value);
                    ReportPropertyChanging("RuleId");
                    _RuleId = StructuralObject.SetValidValue(value, "RuleId");
                    ReportPropertyChanged("RuleId");
                    OnRuleIdChanged();
                }
            }
        }
        private global::System.Int64 _RuleId;
        partial void OnRuleIdChanging(global::System.Int64 value);
        partial void OnRuleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RuleName
        {
            get
            {
                return _RuleName;
            }
            set
            {
                OnRuleNameChanging(value);
                ReportPropertyChanging("RuleName");
                _RuleName = StructuralObject.SetValidValue(value, false, "RuleName");
                ReportPropertyChanged("RuleName");
                OnRuleNameChanged();
            }
        }
        private global::System.String _RuleName;
        partial void OnRuleNameChanging(global::System.String value);
        partial void OnRuleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RuleDescription
        {
            get
            {
                return _RuleDescription;
            }
            set
            {
                OnRuleDescriptionChanging(value);
                ReportPropertyChanging("RuleDescription");
                _RuleDescription = StructuralObject.SetValidValue(value, true, "RuleDescription");
                ReportPropertyChanged("RuleDescription");
                OnRuleDescriptionChanged();
            }
        }
        private global::System.String _RuleDescription;
        partial void OnRuleDescriptionChanging(global::System.String value);
        partial void OnRuleDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RuleValue
        {
            get
            {
                return _RuleValue;
            }
            set
            {
                OnRuleValueChanging(value);
                ReportPropertyChanging("RuleValue");
                _RuleValue = StructuralObject.SetValidValue(value, false, "RuleValue");
                ReportPropertyChanged("RuleValue");
                OnRuleValueChanged();
            }
        }
        private global::System.String _RuleValue;
        partial void OnRuleValueChanging(global::System.String value);
        partial void OnRuleValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerDataModel.Domain", Name="Option")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Option : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Option object.
        /// </summary>
        /// <param name="organizationId">Initial value of the OrganizationId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="navigationId">Initial value of the NavigationId property.</param>
        /// <param name="gridPageSize">Initial value of the GridPageSize property.</param>
        public static Option CreateOption(global::System.Int64 organizationId, global::System.Int64 userId, global::System.Int64 navigationId, global::System.Int32 gridPageSize)
        {
            Option option = new Option();
            option.OrganizationId = organizationId;
            option.UserId = userId;
            option.NavigationId = navigationId;
            option.GridPageSize = gridPageSize;
            return option;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 OrganizationId
        {
            get
            {
                return _OrganizationId;
            }
            set
            {
                if (_OrganizationId != value)
                {
                    OnOrganizationIdChanging(value);
                    ReportPropertyChanging("OrganizationId");
                    _OrganizationId = StructuralObject.SetValidValue(value, "OrganizationId");
                    ReportPropertyChanged("OrganizationId");
                    OnOrganizationIdChanged();
                }
            }
        }
        private global::System.Int64 _OrganizationId;
        partial void OnOrganizationIdChanging(global::System.Int64 value);
        partial void OnOrganizationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 NavigationId
        {
            get
            {
                return _NavigationId;
            }
            set
            {
                OnNavigationIdChanging(value);
                ReportPropertyChanging("NavigationId");
                _NavigationId = StructuralObject.SetValidValue(value, "NavigationId");
                ReportPropertyChanged("NavigationId");
                OnNavigationIdChanged();
            }
        }
        private global::System.Int64 _NavigationId;
        partial void OnNavigationIdChanging(global::System.Int64 value);
        partial void OnNavigationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ControlSettings
        {
            get
            {
                return _ControlSettings;
            }
            set
            {
                OnControlSettingsChanging(value);
                ReportPropertyChanging("ControlSettings");
                _ControlSettings = StructuralObject.SetValidValue(value, true, "ControlSettings");
                ReportPropertyChanged("ControlSettings");
                OnControlSettingsChanged();
            }
        }
        private global::System.String _ControlSettings;
        partial void OnControlSettingsChanging(global::System.String value);
        partial void OnControlSettingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GridPageSize
        {
            get
            {
                return _GridPageSize;
            }
            set
            {
                OnGridPageSizeChanging(value);
                ReportPropertyChanging("GridPageSize");
                _GridPageSize = StructuralObject.SetValidValue(value, "GridPageSize");
                ReportPropertyChanged("GridPageSize");
                OnGridPageSizeChanged();
            }
        }
        private global::System.Int32 _GridPageSize;
        partial void OnGridPageSizeChanging(global::System.Int32 value);
        partial void OnGridPageSizeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerDataModel.Domain", Name="Organization")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Organization : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Organization object.
        /// </summary>
        /// <param name="organizationId">Initial value of the OrganizationId property.</param>
        /// <param name="organizationCode">Initial value of the OrganizationCode property.</param>
        /// <param name="organizationName">Initial value of the OrganizationName property.</param>
        /// <param name="addressID">Initial value of the AddressID property.</param>
        public static Organization CreateOrganization(global::System.Int32 organizationId, global::System.String organizationCode, global::System.String organizationName, global::System.Int64 addressID)
        {
            Organization organization = new Organization();
            organization.OrganizationId = organizationId;
            organization.OrganizationCode = organizationCode;
            organization.OrganizationName = organizationName;
            organization.AddressID = addressID;
            return organization;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrganizationId
        {
            get
            {
                return _OrganizationId;
            }
            set
            {
                if (_OrganizationId != value)
                {
                    OnOrganizationIdChanging(value);
                    ReportPropertyChanging("OrganizationId");
                    _OrganizationId = StructuralObject.SetValidValue(value, "OrganizationId");
                    ReportPropertyChanged("OrganizationId");
                    OnOrganizationIdChanged();
                }
            }
        }
        private global::System.Int32 _OrganizationId;
        partial void OnOrganizationIdChanging(global::System.Int32 value);
        partial void OnOrganizationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrganizationCode
        {
            get
            {
                return _OrganizationCode;
            }
            set
            {
                OnOrganizationCodeChanging(value);
                ReportPropertyChanging("OrganizationCode");
                _OrganizationCode = StructuralObject.SetValidValue(value, false, "OrganizationCode");
                ReportPropertyChanged("OrganizationCode");
                OnOrganizationCodeChanged();
            }
        }
        private global::System.String _OrganizationCode;
        partial void OnOrganizationCodeChanging(global::System.String value);
        partial void OnOrganizationCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrganizationName
        {
            get
            {
                return _OrganizationName;
            }
            set
            {
                OnOrganizationNameChanging(value);
                ReportPropertyChanging("OrganizationName");
                _OrganizationName = StructuralObject.SetValidValue(value, false, "OrganizationName");
                ReportPropertyChanged("OrganizationName");
                OnOrganizationNameChanged();
            }
        }
        private global::System.String _OrganizationName;
        partial void OnOrganizationNameChanging(global::System.String value);
        partial void OnOrganizationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true, "PhoneNumber");
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FaxNumber
        {
            get
            {
                return _FaxNumber;
            }
            set
            {
                OnFaxNumberChanging(value);
                ReportPropertyChanging("FaxNumber");
                _FaxNumber = StructuralObject.SetValidValue(value, true, "FaxNumber");
                ReportPropertyChanged("FaxNumber");
                OnFaxNumberChanged();
            }
        }
        private global::System.String _FaxNumber;
        partial void OnFaxNumberChanging(global::System.String value);
        partial void OnFaxNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ParentOrganization
        {
            get
            {
                return _ParentOrganization;
            }
            set
            {
                OnParentOrganizationChanging(value);
                ReportPropertyChanging("ParentOrganization");
                _ParentOrganization = StructuralObject.SetValidValue(value, true, "ParentOrganization");
                ReportPropertyChanged("ParentOrganization");
                OnParentOrganizationChanged();
            }
        }
        private global::System.String _ParentOrganization;
        partial void OnParentOrganizationChanging(global::System.String value);
        partial void OnParentOrganizationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AddressID
        {
            get
            {
                return _AddressID;
            }
            set
            {
                OnAddressIDChanging(value);
                ReportPropertyChanging("AddressID");
                _AddressID = StructuralObject.SetValidValue(value, "AddressID");
                ReportPropertyChanged("AddressID");
                OnAddressIDChanged();
            }
        }
        private global::System.Int64 _AddressID;
        partial void OnAddressIDChanging(global::System.Int64 value);
        partial void OnAddressIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerDataModel.Domain", Name="Site")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Site : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Site object.
        /// </summary>
        /// <param name="siteId">Initial value of the SiteId property.</param>
        /// <param name="organizationId">Initial value of the OrganizationId property.</param>
        /// <param name="siteTypeId">Initial value of the SiteTypeId property.</param>
        /// <param name="siteName">Initial value of the SiteName property.</param>
        /// <param name="timeZoneId">Initial value of the TimeZoneId property.</param>
        /// <param name="addressId">Initial value of the AddressId property.</param>
        public static Site CreateSite(global::System.Int64 siteId, global::System.Int64 organizationId, global::System.Int64 siteTypeId, global::System.String siteName, global::System.Int64 timeZoneId, global::System.Int64 addressId)
        {
            Site site = new Site();
            site.SiteId = siteId;
            site.OrganizationId = organizationId;
            site.SiteTypeId = siteTypeId;
            site.SiteName = siteName;
            site.TimeZoneId = timeZoneId;
            site.AddressId = addressId;
            return site;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SiteId
        {
            get
            {
                return _SiteId;
            }
            set
            {
                if (_SiteId != value)
                {
                    OnSiteIdChanging(value);
                    ReportPropertyChanging("SiteId");
                    _SiteId = StructuralObject.SetValidValue(value, "SiteId");
                    ReportPropertyChanged("SiteId");
                    OnSiteIdChanged();
                }
            }
        }
        private global::System.Int64 _SiteId;
        partial void OnSiteIdChanging(global::System.Int64 value);
        partial void OnSiteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 OrganizationId
        {
            get
            {
                return _OrganizationId;
            }
            set
            {
                OnOrganizationIdChanging(value);
                ReportPropertyChanging("OrganizationId");
                _OrganizationId = StructuralObject.SetValidValue(value, "OrganizationId");
                ReportPropertyChanged("OrganizationId");
                OnOrganizationIdChanged();
            }
        }
        private global::System.Int64 _OrganizationId;
        partial void OnOrganizationIdChanging(global::System.Int64 value);
        partial void OnOrganizationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SiteTypeId
        {
            get
            {
                return _SiteTypeId;
            }
            set
            {
                OnSiteTypeIdChanging(value);
                ReportPropertyChanging("SiteTypeId");
                _SiteTypeId = StructuralObject.SetValidValue(value, "SiteTypeId");
                ReportPropertyChanged("SiteTypeId");
                OnSiteTypeIdChanged();
            }
        }
        private global::System.Int64 _SiteTypeId;
        partial void OnSiteTypeIdChanging(global::System.Int64 value);
        partial void OnSiteTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SiteName
        {
            get
            {
                return _SiteName;
            }
            set
            {
                OnSiteNameChanging(value);
                ReportPropertyChanging("SiteName");
                _SiteName = StructuralObject.SetValidValue(value, false, "SiteName");
                ReportPropertyChanged("SiteName");
                OnSiteNameChanged();
            }
        }
        private global::System.String _SiteName;
        partial void OnSiteNameChanging(global::System.String value);
        partial void OnSiteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SiteCode
        {
            get
            {
                return _SiteCode;
            }
            set
            {
                OnSiteCodeChanging(value);
                ReportPropertyChanging("SiteCode");
                _SiteCode = StructuralObject.SetValidValue(value, true, "SiteCode");
                ReportPropertyChanged("SiteCode");
                OnSiteCodeChanged();
            }
        }
        private global::System.String _SiteCode;
        partial void OnSiteCodeChanging(global::System.String value);
        partial void OnSiteCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TimeZoneId
        {
            get
            {
                return _TimeZoneId;
            }
            set
            {
                OnTimeZoneIdChanging(value);
                ReportPropertyChanging("TimeZoneId");
                _TimeZoneId = StructuralObject.SetValidValue(value, "TimeZoneId");
                ReportPropertyChanged("TimeZoneId");
                OnTimeZoneIdChanged();
            }
        }
        private global::System.Int64 _TimeZoneId;
        partial void OnTimeZoneIdChanging(global::System.Int64 value);
        partial void OnTimeZoneIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AddressId
        {
            get
            {
                return _AddressId;
            }
            set
            {
                OnAddressIdChanging(value);
                ReportPropertyChanging("AddressId");
                _AddressId = StructuralObject.SetValidValue(value, "AddressId");
                ReportPropertyChanged("AddressId");
                OnAddressIdChanged();
            }
        }
        private global::System.Int64 _AddressId;
        partial void OnAddressIdChanging(global::System.Int64 value);
        partial void OnAddressIdChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerDataModel.Domain", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="organization">Initial value of the Organization property.</param>
        /// <param name="userTypeId">Initial value of the UserTypeId property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        public static User CreateUser(global::System.Int32 userId, global::System.Int32 organization, global::System.Int32 userTypeId, global::System.String firstName, global::System.String lastName)
        {
            User user = new User();
            user.UserId = userId;
            user.Organization = organization;
            user.UserTypeId = userTypeId;
            user.FirstName = firstName;
            user.LastName = lastName;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, "UserId");
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Organization
        {
            get
            {
                return _Organization;
            }
            set
            {
                OnOrganizationChanging(value);
                ReportPropertyChanging("Organization");
                _Organization = StructuralObject.SetValidValue(value, "Organization");
                ReportPropertyChanged("Organization");
                OnOrganizationChanged();
            }
        }
        private global::System.Int32 _Organization;
        partial void OnOrganizationChanging(global::System.Int32 value);
        partial void OnOrganizationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserTypeId
        {
            get
            {
                return _UserTypeId;
            }
            set
            {
                OnUserTypeIdChanging(value);
                ReportPropertyChanging("UserTypeId");
                _UserTypeId = StructuralObject.SetValidValue(value, "UserTypeId");
                ReportPropertyChanged("UserTypeId");
                OnUserTypeIdChanged();
            }
        }
        private global::System.Int32 _UserTypeId;
        partial void OnUserTypeIdChanging(global::System.Int32 value);
        partial void OnUserTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true, "PhoneNumber");
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true, "EmailAddress");
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitName
        {
            get
            {
                return _UnitName;
            }
            set
            {
                OnUnitNameChanging(value);
                ReportPropertyChanging("UnitName");
                _UnitName = StructuralObject.SetValidValue(value, true, "UnitName");
                ReportPropertyChanged("UnitName");
                OnUnitNameChanged();
            }
        }
        private global::System.String _UnitName;
        partial void OnUnitNameChanging(global::System.String value);
        partial void OnUnitNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitNumber
        {
            get
            {
                return _UnitNumber;
            }
            set
            {
                OnUnitNumberChanging(value);
                ReportPropertyChanging("UnitNumber");
                _UnitNumber = StructuralObject.SetValidValue(value, true, "UnitNumber");
                ReportPropertyChanged("UnitNumber");
                OnUnitNumberChanged();
            }
        }
        private global::System.String _UnitNumber;
        partial void OnUnitNumberChanging(global::System.String value);
        partial void OnUnitNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Department
        {
            get
            {
                return _Department;
            }
            set
            {
                OnDepartmentChanging(value);
                ReportPropertyChanging("Department");
                _Department = StructuralObject.SetValidValue(value, true, "Department");
                ReportPropertyChanged("Department");
                OnDepartmentChanged();
            }
        }
        private global::System.String _Department;
        partial void OnDepartmentChanging(global::System.String value);
        partial void OnDepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SiteId
        {
            get
            {
                return _SiteId;
            }
            set
            {
                OnSiteIdChanging(value);
                ReportPropertyChanging("SiteId");
                _SiteId = StructuralObject.SetValidValue(value, "SiteId");
                ReportPropertyChanged("SiteId");
                OnSiteIdChanged();
            }
        }
        private Nullable<global::System.Int64> _SiteId;
        partial void OnSiteIdChanging(Nullable<global::System.Int64> value);
        partial void OnSiteIdChanged();

        #endregion

    }

    #endregion

}
