//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCustomerIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.CredentialRoles = new HashSet<CredentialRole>();
        }
    
        public long RoleId { get; set; }
        public long RoleTypeId { get; set; }
        public long OrganizationId { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public bool DefaultRoleFlag { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<CredentialRole> CredentialRoles { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual RoleType RoleType { get; set; }
    }
}
