//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCustomerIntegration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBIntegrationEntities : DbContext
    {
        public DBIntegrationEntities()
            : base("name=DBIntegrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<AddressType> AddressTypes { get; set; }
        public DbSet<AssociationType> AssociationTypes { get; set; }
        public DbSet<Catalog> Catalogs { get; set; }
        public DbSet<Credential> Credentials { get; set; }
        public DbSet<CredentialRole> CredentialRoles { get; set; }
        public DbSet<CycleFrequency> CycleFrequencies { get; set; }
        public DbSet<DeliveryMethod> DeliveryMethods { get; set; }
        public DbSet<Navigation> Navigations { get; set; }
        public DbSet<Operation> Operations { get; set; }
        public DbSet<OperationType> OperationTypes { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<OrganizationAdministrator> OrganizationAdministrators { get; set; }
        public DbSet<OrganizationCycleFrequency> OrganizationCycleFrequencies { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<RegionType> RegionTypes { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RoleType> RoleTypes { get; set; }
        public DbSet<Rule> Rules { get; set; }
        public DbSet<RuleSet> RuleSets { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<SiteAssociation> SiteAssociations { get; set; }
        public DbSet<SiteType> SiteTypes { get; set; }
        public DbSet<SupportInfo> SupportInfoes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TimeZone> TimeZones { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<ValueType> ValueTypes { get; set; }
    }
}
