//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCustomerIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleSet
    {
        public long RuleSetId { get; set; }
        public long OrganizationId { get; set; }
        public long AssociationId { get; set; }
        public long AssociationTypeId { get; set; }
        public long ApplicationId { get; set; }
        public long RuleId { get; set; }
        public string RuleValue { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual AssociationType AssociationType { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Rule Rule { get; set; }
    }
}
